package com.konexio.bank.ledger;

import com.konexio.bank.shared.money.Money;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * A journal entry that is on the books.
 *
 * @param reference the customer-facing receipt reference,
 *                  e.g. {@code KNX-TR-260922-0433}, generated by the database
 */
public record PostedEntry(
        UUID id,
        String reference,
        EntryType entryType,
        SourceType sourceType,
        UUID sourceId,
        String description,
        Instant postedAt,
        List<PostedLine> lines) {

    public PostedEntry {
        lines = List.copyOf(lines);
    }

    /** The balance of {@code accountId} after this entry, for the confirmation screen. */
    public Optional<Money> balanceAfterFor(UUID accountId) {
        return lines.stream()
                .filter(line -> line.accountId().equals(accountId))
                .reduce((first, second) -> second)
                .map(PostedLine::balanceAfter);
    }
}
