package com.konexio.bank.ledger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.konexio.bank.AbstractIntegrationTest;
import com.konexio.bank.shared.actor.Actor;
import com.konexio.bank.shared.actor.ActorContext;
import com.konexio.bank.shared.error.ConflictException;
import com.konexio.bank.shared.error.UnprocessableEntityException;
import com.konexio.bank.shared.money.Money;
import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;

/**
 * The ledger against a real database, because almost everything it promises is
 * enforced there: the balance trigger, the lock it takes, the overdraft CHECK,
 * the deferred balanced-entry constraint and the statement view.
 *
 * <p>No endpoints — Phase 3 ships none — so these call {@link LedgerApi}
 * directly, against the GL accounts seeded by {@code V17}.
 */
class LedgerPostingIT extends AbstractIntegrationTest {

    private static final String PIN = "2483";

    @Autowired
    private LedgerApi ledger;

    private UUID customerId;
    private UUID mainAccountId;
    private UUID savingsAccountId;
    private UUID mpesaClearingId;
    private UUID feeIncomeId;

    @BeforeEach
    void openAccounts() {
        String phone = uniquePhone();
        customerId = registerCustomer(phone, uniqueNationalId(), PIN);
        String accessToken = String.valueOf(login(phone, PIN).get("accessToken"));
        mainAccountId = openAccountFor(accessToken, "MAIN");
        savingsAccountId = openAccountFor(accessToken, "SAVINGS");
        mpesaClearingId = internalAccountId("MPESA_CLEARING");
        feeIncomeId = internalAccountId("FEE_INCOME");
    }

    @Test
    @DisplayName("a deposit credits the customer and debits the clearing account, and both balances move")
    void postsADeposit() {
        BigDecimal clearingBefore = balanceOf(mpesaClearingId);

        PostedEntry entry = deposit("5000.00");

        // The reference is the customer's receipt number, generated by the database.
        assertThat(entry.reference()).matches("^KNX-DP-[0-9]{6}-[0-9]{4,}$");
        assertThat(entry.postedAt()).isNotNull();
        assertThat(entry.balanceAfterFor(mainAccountId)).contains(money("5000.00"));
        assertThat(balanceOf(mainAccountId)).isEqualByComparingTo("5000.00");

        // Same direction, opposite effect: the clearing account's normal balance is
        // DEBIT, so debiting it raises it while crediting the customer raises theirs.
        assertThat(balanceOf(mpesaClearingId)).isEqualByComparingTo(clearingBefore.add(new BigDecimal("5000.00")));
    }

    @Test
    @DisplayName("a fee rides in the same entry as the transfer it is charged on")
    void postsATransferWithAFee() {
        deposit("5000.00");
        BigDecimal feeIncomeBefore = balanceOf(feeIncomeId);

        PostedEntry entry = ledger.post(new PostEntryCommand(
                EntryType.TRANSFER, SourceType.PAYMENT, UUID.randomUUID(), "Cement, invoice 118",
                List.of(
                        PostingLine.debit(mainAccountId, money("3550.00")),
                        PostingLine.credit(savingsAccountId, money("3500.00")),
                        PostingLine.credit(feeIncomeId, money("50.00")))));

        assertThat(entry.lines()).hasSize(3);
        assertThat(balanceOf(mainAccountId)).isEqualByComparingTo("1450.00");
        assertThat(balanceOf(savingsAccountId)).isEqualByComparingTo("3500.00");
        assertThat(balanceOf(feeIncomeId)).isEqualByComparingTo(feeIncomeBefore.add(new BigDecimal("50.00")));
        assertThat(entry.balanceAfterFor(mainAccountId)).contains(money("1450.00"));
    }

    @Test
    @DisplayName("spending more than the account holds is a 422, and nothing moves")
    void refusesAnOverdraft() {
        deposit("1000.00");

        assertThatThrownBy(() -> ledger.post(new PostEntryCommand(
                EntryType.TRANSFER, SourceType.PAYMENT, UUID.randomUUID(), "Too much",
                List.of(
                        PostingLine.debit(mainAccountId, money("1500.00")),
                        PostingLine.credit(savingsAccountId, money("1500.00"))))))
                .isInstanceOf(UnprocessableEntityException.class)
                .hasMessageContaining("below zero");

        // The whole entry rolled back, including the leg that would have succeeded.
        assertThat(balanceOf(mainAccountId)).isEqualByComparingTo("1000.00");
        assertThat(balanceOf(savingsAccountId)).isEqualByComparingTo("0.00");
        assertThat(countRows("select count(*) from ledger.journal_entry where description = 'Too much'"))
                .isZero();
    }

    @Test
    @DisplayName("a closed account can neither receive nor send")
    void refusesAClosedAccount() {
        close(savingsAccountId);
        deposit("1000.00");

        assertThatThrownBy(() -> ledger.post(new PostEntryCommand(
                EntryType.TRANSFER, SourceType.PAYMENT, UUID.randomUUID(), "To a closed account",
                List.of(
                        PostingLine.debit(mainAccountId, money("100.00")),
                        PostingLine.credit(savingsAccountId, money("100.00"))))))
                .isInstanceOf(ConflictException.class)
                .hasMessageContaining("closed");

        assertThat(balanceOf(mainAccountId)).isEqualByComparingTo("1000.00");
    }

    @Test
    @DisplayName("an amount in the wrong currency is refused rather than converted")
    void refusesACurrencyMismatch() {
        assertThatThrownBy(() -> ledger.post(new PostEntryCommand(
                EntryType.DEPOSIT, SourceType.PAYMENT, UUID.randomUUID(), "Dollars into a shilling account",
                List.of(
                        PostingLine.debit(mpesaClearingId, usd("100.00")),
                        PostingLine.credit(mainAccountId, usd("100.00"))))))
                .isInstanceOf(UnprocessableEntityException.class)
                .hasMessageContaining("currency");

        assertThat(balanceOf(mainAccountId)).isEqualByComparingTo("0.00");
    }

    @Test
    @DisplayName("posting to an account that does not exist is refused")
    void refusesAnUnknownAccount() {
        assertThatThrownBy(() -> ledger.post(new PostEntryCommand(
                EntryType.DEPOSIT, SourceType.PAYMENT, UUID.randomUUID(), "Into nowhere",
                List.of(
                        PostingLine.debit(mpesaClearingId, money("100.00")),
                        PostingLine.credit(UUID.randomUUID(), money("100.00"))))))
                .isInstanceOf(UnprocessableEntityException.class);
    }

    @Test
    @DisplayName("an unbalanced entry inserted around the application is still refused, at COMMIT")
    void theDatabaseIsTheLastWordOnBalance() {
        UUID entryId = jdbcClient
                .sql("""
                        insert into ledger.journal_entry (entry_type, source_type, source_id, description)
                        values ('DEPOSIT', 'PAYMENT', ?, 'Half an entry')
                        returning id
                        """)
                .param(UUID.randomUUID())
                .query(UUID.class)
                .single();

        // One line, no counterpart: trg_posting_balanced is DEFERRABLE INITIALLY
        // DEFERRED, so this survives the INSERT and dies at COMMIT.
        assertThatThrownBy(() -> jdbcClient
                .sql("""
                        insert into ledger.posting (journal_entry_id, account_id, direction, amount, currency)
                        values (?, ?, 'CREDIT', 1000.00, 'KES')
                        """)
                .params(List.of(entryId, mainAccountId))
                .update())
                .isInstanceOf(DataAccessException.class)
                .hasMessageContaining("unbalanced");

        assertThat(balanceOf(mainAccountId)).isEqualByComparingTo("0.00");
    }

    @Test
    @DisplayName("the statement shows the customer's own legs, not the bank's side of the entry")
    void statementHidesTheInternalLegs() {
        deposit("5000.00");
        ledger.post(new PostEntryCommand(
                EntryType.TRANSFER, SourceType.PAYMENT, UUID.randomUUID(), "Cement, invoice 118",
                List.of(
                        PostingLine.debit(mainAccountId, money("3550.00")),
                        PostingLine.credit(savingsAccountId, money("3500.00")),
                        PostingLine.credit(feeIncomeId, money("50.00")))));

        Page<StatementLine> statement =
                ledger.statement(StatementQuery.forCustomer(customerId), PageRequest.of(0, 20));

        // Five postings were written; three of them are this customer's.
        assertThat(statement.getTotalElements()).isEqualTo(3);
        assertThat(statement.getContent()).extracting(StatementLine::accountId)
                .containsOnly(mainAccountId, savingsAccountId);
        assertThat(statement.getContent()).allSatisfy(line -> {
            assertThat(line.customerId()).isEqualTo(customerId);
            assertThat(line.accountMaskedNumber()).startsWith("••••");
        });

        // Newest first: the transfer's two legs, then the deposit.
        assertThat(statement.getContent().getLast().direction()).isEqualTo(StatementDirection.IN);
        assertThat(statement.getContent().getLast().signedAmount()).isEqualTo(money("5000.00"));

        StatementLine moneyOut = statement.getContent().stream()
                .filter(line -> line.direction() == StatementDirection.OUT)
                .findFirst()
                .orElseThrow();
        assertThat(moneyOut.amount()).isEqualTo(money("3550.00"));
        assertThat(moneyOut.signedAmount()).isEqualTo(money("-3550.00"));
        assertThat(moneyOut.balanceAfter()).isEqualTo(money("1450.00"));
    }

    @Test
    @DisplayName("the statement filters by account and by direction")
    void statementFilters() {
        deposit("5000.00");
        ledger.post(new PostEntryCommand(
                EntryType.TRANSFER, SourceType.PAYMENT, UUID.randomUUID(), "To savings",
                List.of(
                        PostingLine.debit(mainAccountId, money("2000.00")),
                        PostingLine.credit(savingsAccountId, money("2000.00")))));

        StatementQuery mine = StatementQuery.forCustomer(customerId);
        assertThat(ledger.statement(mine.onAccount(savingsAccountId), PageRequest.of(0, 20)).getTotalElements())
                .isEqualTo(1);
        assertThat(ledger.statement(mine.showing(StatementDirection.OUT), PageRequest.of(0, 20)).getTotalElements())
                .isEqualTo(1);
        assertThat(ledger.statement(mine.onAccount(mainAccountId), PageRequest.of(0, 1)).getTotalElements())
                .isEqualTo(2);
        assertThat(ledger.statement(mine.onAccount(mainAccountId), PageRequest.of(0, 1)).getContent())
                .hasSize(1);
    }

    @Test
    @DisplayName("one customer's statement never contains another's lines")
    void statementIsScopedToOneCustomer() {
        deposit("5000.00");

        String otherPhone = uniquePhone();
        UUID otherCustomerId = registerCustomer(otherPhone, uniqueNationalId(), PIN);

        assertThat(ledger.statement(StatementQuery.forCustomer(otherCustomerId), PageRequest.of(0, 20))
                .getTotalElements())
                .isZero();
    }

    @Test
    @DisplayName("entries can be found again by the record that caused them")
    void findsEntriesBySource() {
        UUID intentId = UUID.randomUUID();
        PostedEntry posted = ledger.post(new PostEntryCommand(
                EntryType.DEPOSIT, SourceType.PAYMENT, intentId, "M-Pesa deposit",
                List.of(
                        PostingLine.debit(mpesaClearingId, money("750.00")),
                        PostingLine.credit(mainAccountId, money("750.00")))));

        assertThat(ledger.findBySource(SourceType.PAYMENT, intentId))
                .extracting(PostedEntry::id)
                .containsExactly(posted.id());
        assertThat(ledger.findBySource(SourceType.PAYMENT, UUID.randomUUID())).isEmpty();

        PostedEntry reread = ledger.find(posted.id()).orElseThrow();
        assertThat(reread.reference()).isEqualTo(posted.reference());
        assertThat(reread.lines()).extracting(PostedLine::amount).containsOnly(money("750.00"));
        assertThat(reread.balanceAfterFor(mainAccountId)).contains(money("750.00"));
    }

    @Test
    @DisplayName("the entry records who posted it, and the audit trail records the request")
    void attributesThePoster() {
        PostedEntry entry = ActorContext.call(
                Actor.customer(customerId),
                () -> deposit("2500.00"));

        Map<String, Object> row = jdbcClient
                .sql("select posted_by_type, posted_by_id::text as posted_by_id from ledger.journal_entry where id = ?")
                .param(entry.id())
                .query()
                .singleRow();
        assertThat(row.get("posted_by_type")).isEqualTo("CUSTOMER");
        assertThat(row.get("posted_by_id")).isEqualTo(customerId.toString());

        Map<String, Object> audit = jdbcClient
                .sql("""
                        select action, actor_type, details ->> 'reference' as reference
                          from audit.audit_log
                         where resource_id = ? and resource_type = 'JOURNAL_ENTRY'
                        """)
                .param(entry.id())
                .query()
                .singleRow();
        assertThat(audit.get("action")).isEqualTo("JOURNAL_ENTRY_POSTED");
        assertThat(audit.get("actor_type")).isEqualTo("CUSTOMER");
        assertThat(audit.get("reference")).isEqualTo(entry.reference());
    }

    @Test
    @DisplayName("without an actor in scope the books say SYSTEM, not nobody")
    void defaultsToSystem() {
        PostedEntry entry = deposit("100.00");

        assertThat(jdbcClient.sql("select posted_by_type from ledger.journal_entry where id = ?")
                .param(entry.id())
                .query(String.class)
                .single())
                .isEqualTo("SYSTEM");
    }

    @Test
    @DisplayName("two entries never share a reference")
    void referencesAreUnique() {
        PostedEntry first = deposit("100.00");
        PostedEntry second = deposit("200.00");

        assertThat(first.reference()).isNotEqualTo(second.reference());
        assertThat(suffixOf(second)).isGreaterThan(suffixOf(first));
    }

    @Test
    @DisplayName("a reversal undoes an entry by mirroring it, leaving the original untouched")
    void reversesAnEntry() {
        PostedEntry deposit = deposit("4000.00");
        assertThat(balanceOf(mainAccountId)).isEqualByComparingTo("4000.00");

        PostedEntry reversal = ledger.reverse(deposit.id(), "Reversal: test");

        assertThat(reversal.reference()).matches("^KNX-RV-[0-9]{6}-[0-9]{4,}$");
        assertThat(reversal.entryType()).isEqualTo(EntryType.REVERSAL);
        assertThat(balanceOf(mainAccountId)).isEqualByComparingTo("0.00");

        // The original is still exactly as it was posted: correction is a second
        // entry, never an edit.
        PostedEntry original = ledger.find(deposit.id()).orElseThrow();
        assertThat(original.lines()).hasSize(2);
        assertThat(original.balanceAfterFor(mainAccountId)).contains(money("4000.00"));
        assertThat(countRows("""
                select count(*) from ledger.journal_entry where reverses_entry_id = '%s'
                """.formatted(deposit.id())))
                .isEqualTo(1);
    }

    @Test
    @DisplayName("an entry can only be reversed once, and the database is what says so")
    void refusesASecondReversal() {
        PostedEntry deposit = deposit("1000.00");
        ledger.reverse(deposit.id(), "Reversal: first");

        assertThatThrownBy(() -> ledger.reverse(deposit.id(), "Reversal: second"))
                .isInstanceOf(DataAccessException.class);
        assertThat(balanceOf(mainAccountId)).isEqualByComparingTo("0.00");
    }

    @Test
    @DisplayName("reversing an entry that does not exist is a 404")
    void refusesToReverseNothing() {
        assertThatThrownBy(() -> ledger.reverse(UUID.randomUUID(), "Reversal: nothing"))
                .isInstanceOf(com.konexio.bank.shared.error.ResourceNotFoundException.class);
    }

    @Test
    @DisplayName("a REVERSAL cannot be posted through post(): it has to name what it reverses")
    void refusesReversalsForNow() {
        assertThatThrownBy(() -> ledger.post(new PostEntryCommand(
                EntryType.REVERSAL, SourceType.ADJUSTMENT, UUID.randomUUID(), "Undo",
                List.of(
                        PostingLine.debit(mainAccountId, money("100.00")),
                        PostingLine.credit(mpesaClearingId, money("100.00"))))))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("REVERSAL");
    }

    private PostedEntry deposit(String amount) {
        return ledger.post(new PostEntryCommand(
                EntryType.DEPOSIT, SourceType.PAYMENT, UUID.randomUUID(), "M-Pesa deposit",
                List.of(
                        PostingLine.debit(mpesaClearingId, money("KES", amount)),
                        PostingLine.credit(mainAccountId, money("KES", amount)))));
    }

    private void close(UUID accountId) {
        jdbcClient.sql("""
                update account.account
                   set status = 'CLOSED', closed_at = now(), closure_reason = 'NOT_USED', closure_reference = ?
                 where id = ?
                """)
                .params(List.of("KNX-CL-" + accountId, accountId))
                .update();
    }

    private static int suffixOf(PostedEntry entry) {
        return Integer.parseInt(entry.reference().substring(entry.reference().lastIndexOf('-') + 1));
    }

    private static Money money(String amount) {
        return Money.kes(amount);
    }

    private static Money money(String currency, String amount) {
        return Money.of(new BigDecimal(amount), currency);
    }

    private static Money usd(String amount) {
        return money("USD", amount);
    }
}
