-- Development seed. Safe to re-run: every statement is guarded.
--
--   docker exec -i bank-postgres-1 psql -U konexio -d konexio < scripts/dev-seed.sql
--
-- Two problems this solves on a fresh database:
--
--   1. Accounts start empty, and a deposit made in the app stays PROCESSING until
--      a provider callback settles it — which nothing sends locally. This posts
--      an opening balance through the ledger so there is money to move.
--   2. Fees and limits are deliberately unseeded, because they are decisions
--      somebody signs off. Until rows exist, every fee reads KES 0.00 and the
--      amount screens state no limits. (Loan pricing is not here: V20 seeds it.)
--
-- Never run this against a real database. `approved_by` says so on every row.

begin;

-- 1. Opening balance -----------------------------------------------------------
--
-- A balanced journal entry, not an UPDATE of ledger_balance: the balance is
-- maintained by a trigger from the postings, so writing it directly would put
-- the books and the balance out of step. Debit M-Pesa clearing, credit the
-- customer, exactly as a settled deposit does. The reference is generated by
-- ledger.set_journal_reference().

with target as (
    select a.id, a.currency
      from account.account a
     where a.account_class = 'CUSTOMER'
       and a.account_type = 'MAIN'
       and a.status <> 'CLOSED'
       and a.ledger_balance = 0
), entry as (
    insert into ledger.journal_entry (entry_type, source_type, source_id, description)
    select 'DEPOSIT', 'ADJUSTMENT', gen_random_uuid(), 'Development opening balance'
      from target
     limit 1
    returning id
)
insert into ledger.posting (journal_entry_id, account_id, direction, amount, currency)
select e.id, clearing.id, 'DEBIT', 50000.00, t.currency
  from entry e
  cross join target t
  join account.account clearing
    on clearing.account_type = 'MPESA_CLEARING'
   and clearing.currency = t.currency
union all
select e.id, t.id, 'CREDIT', 50000.00, t.currency
  from entry e
  cross join target t;

-- 2. Transaction limits --------------------------------------------------------
--
-- What a customer may move in one payment, by KYC level. Without these the
-- application logs "payments are running unlimited" on every quote.

insert into payment.transaction_limit
    (intent_type, channel, kyc_level, valid_during, min_amount, max_amount, daily_max_amount, approved_by)
select v.intent_type, v.channel, v.kyc_level, daterange(current_date - 1, null),
       v.min_amount, v.max_amount, v.daily_max_amount, 'dev-seed'
  from (values
        ('DEPOSIT',    'MPESA',    'VERIFIED', 100.00, 150000.00, 300000.00),
        ('DEPOSIT',    'MPESA',    'BASIC',    100.00,  35000.00,  70000.00),
        ('DEPOSIT',    'CARD',     'VERIFIED', 100.00, 150000.00, 300000.00),
        ('DEPOSIT',    'CARD',     'BASIC',    100.00,  35000.00,  70000.00),
        ('DEPOSIT',    'AGENT',    'VERIFIED', 100.00, 150000.00, 300000.00),
        ('DEPOSIT',    'AGENT',    'BASIC',    100.00,  35000.00,  70000.00),
        ('WITHDRAWAL', 'MPESA',    'VERIFIED', 100.00,  50000.00, 100000.00),
        ('WITHDRAWAL', 'MPESA',    'BASIC',    100.00,  20000.00,  40000.00),
        ('WITHDRAWAL', 'AGENT',    'VERIFIED', 100.00,  50000.00, 100000.00),
        ('WITHDRAWAL', 'AGENT',    'BASIC',    100.00,  20000.00,  40000.00),
        ('TRANSFER',   'INTERNAL', 'VERIFIED',  10.00, 500000.00, 1000000.00),
        ('TRANSFER',   'INTERNAL', 'BASIC',     10.00,  50000.00, 100000.00)
       ) as v(intent_type, channel, kyc_level, min_amount, max_amount, daily_max_amount)
 where not exists (
        select 1 from payment.transaction_limit existing
         where existing.intent_type = v.intent_type
           and existing.channel = v.channel
           and existing.kyc_level = v.kyc_level);

-- 3. Fee rules -----------------------------------------------------------------
--
-- Banded by amount, the way a tariff is published. Deposits and internal
-- transfers are free; taking cash out is not.

insert into payment.fee_rule
    (intent_type, channel, min_amount, max_amount, fee, valid_from, approved_by)
select v.intent_type, v.channel, v.min_amount, v.max_amount, v.fee, current_date - 1, 'dev-seed'
  from (values
        ('DEPOSIT',    'MPESA',       0.01, 999999999.99,   0.00),
        ('DEPOSIT',    'CARD',        0.01, 999999999.99,   0.00),
        ('DEPOSIT',    'AGENT',       0.01, 999999999.99,   0.00),
        ('TRANSFER',   'INTERNAL',    0.01, 999999999.99,   0.00),
        ('WITHDRAWAL', 'MPESA',       0.01,      1000.00,  20.00),
        ('WITHDRAWAL', 'MPESA',    1000.01,      5000.00,  50.00),
        ('WITHDRAWAL', 'MPESA',    5000.01, 999999999.99, 100.00),
        ('WITHDRAWAL', 'AGENT',       0.01,      1000.00,  25.00),
        ('WITHDRAWAL', 'AGENT',    1000.01,      5000.00,  60.00),
        ('WITHDRAWAL', 'AGENT',    5000.01, 999999999.99, 120.00)
       ) as v(intent_type, channel, min_amount, max_amount, fee)
 where not exists (
        select 1 from payment.fee_rule existing
         where existing.intent_type = v.intent_type
           and existing.channel = v.channel
           and existing.min_amount = v.min_amount);

commit;

select a.account_number, a.account_type, a.ledger_balance
  from account.account a
 where a.account_class = 'CUSTOMER'
 order by a.account_number;
